language: android

jdk:
  - oraclejdk8

notifications:
  email: false

sudo: false

android:
  components:
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - extra-android-support

before_install:
 - chmod +x gradlew

script:
  - ./gradlew assembleRelease


before_deploy:       # 部署之前
  # 使用 mv 命令进行修改apk文件的名字
  - ls  -h app/build/outputs/apk/release
  - cat app/build/outputs/apk/release/output.json
  #- mv app/build/outputs/apk/app-release-unsigned.apk app/build/outputs/apk/buff.apk  
  - git config --local user.name "indiff"
  - git config --local user.email "indiff@126.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG 
  
deploy:              # 部署
  provider: releases # 部署到GitHub Release，除此之外，Travis CI还支持发布到fir.im、AWS、Google App Engine等
  api_key:           # 填写GitHub的token （Settings -> Personal access tokens -> Generate new token）
    secure: 4f05e951b23586db571b5b4ef735d90bb8506939 
  file: app/build/outputs/apk/app-release-unsigned.apk   # 部署文件路径
  skip_cleanup: true     # 设置为true以跳过清理,不然apk文件就会被清理
  
